listen_addresses = '*'

# --- PGAUDIT ---
shared_preload_libraries = 'pgaudit'
pgaudit.log = 'all'

# --- LOGGING ---
logging_collector = on
log_destination = 'csvlog'
log_directory = 'pg_log'
log_filename = 'audit-%Y-%m-%d.log'
log_rotation_age = 1d
log_rotation_size = 100MB

# Evita duplicação com pgaudit
log_statement = 'none'

# --- PERFORMANCE / SEGURANÇA ---
client_min_messages = notice
log_min_messages = warning
log_min_error_statement = error
